from django.db import models

class Restaurant(models.Model):
    id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    country_code = models.IntegerField()
    city = models.CharField(max_length=100)
    address = models.TextField()
    locality = models.CharField(max_length=100)
    locality_verbose = models.TextField()
    longitude = models.FloatField()
    latitude = models.FloatField()
    cuisines = models.CharField(max_length=255)
    average_cost_for_two = models.IntegerField()
    currency = models.CharField(max_length=50)
    has_table_booking = models.BooleanField()
    has_online_delivery = models.BooleanField()
    is_delivering_now = models.BooleanField()
    switch_to_order_menu = models.BooleanField()
    price_range = models.IntegerField()
    aggregate_rating = models.FloatField()
    rating_color = models.CharField(max_length=50)
    rating_text = models.CharField(max_length=50)
    votes = models.IntegerField()
