# Generated by Django 5.1.6 on 2025-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("country_code", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("locality", models.CharField(max_length=100)),
                ("locality_verbose", models.TextField()),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("cuisines", models.CharField(max_length=255)),
                ("average_cost_for_two", models.IntegerField()),
                ("currency", models.CharField(max_length=50)),
                ("has_table_booking", models.BooleanField()),
                ("has_online_delivery", models.BooleanField()),
                ("is_delivering_now", models.BooleanField()),
                ("switch_to_order_menu", models.BooleanField()),
                ("price_range", models.IntegerField()),
                ("aggregate_rating", models.FloatField()),
                ("rating_color", models.CharField(max_length=50)),
                ("rating_text", models.CharField(max_length=50)),
                ("votes", models.IntegerField()),
            ],
        ),
    ]
